### ISSUE TITLE
Compile error in arduino

### ISSUE THREAD

**Issue by artscienceBLR** [CocoMake7/Getting-Started#3]
Getting compile error for CocoMake7_TouchKeyboard_ONE_velocity_space_RENAMED.ino

**Comment by badgeek** [comment]
can you paste me the error code? and what is the current version of cocomake?

**Comment by badgeek** [comment]
updated the code https://github.com/CocoMake7/Getting-Started/tree/master/Code/CocoMake7_TouchKeyboard_ONE_velocity_space_RENAMED
